//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieWedsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TapPhim
    {
        public string MaTapPhim { get; set; }
        public string TenTapPhim { get; set; }
        public string filePhim { get; set; }
        public string MaPhim { get; set; }
    
        public virtual Phim Phim { get; set; }
    }
}
